### ISSUE TITLE
Nichts kann mehr geschaltet werden

### ISSUE THREAD

**Issue by Dietmar-Franken** [agent4788/SHC_Android_APP#13]
![screenshot_2015-12-20-06-13-43](https://cloud.githubusercontent.com/assets/12993220/11916783/c270c8ca-a6e7-11e5-89ce-76cdbbfbd3cd.png)

**Comment by Dietmar-Franken** [comment]
jetzt ist noch schwarzer Screen gekommen. Crashreport gesendet ;-)

**Comment by agent4788** [comment]
ist mit 1.0.5 behoben
